export const bjjRanks = [
    "White Belt (Kid)",
    "1-Stripe White Belt (Kid)",
    "2-Stripe White Belt (Kid)",
    "3-Stripe White Belt (Kid)",
    "4-Stripe White Belt (Kid)",
    "Grey/White Belt",
    "1-Stripe Grey/White Belt",
    "2-Stripe Grey/White Belt",
    "3-Stripe Grey/White Belt",
    "4-Stripe Grey/White Belt",
    "Grey Belt",
    "1-Stripe Grey Belt",
    "2-Stripe Grey Belt",
    "3-Stripe Grey Belt",
    "4-Stripe Grey Belt",
    "Grey/Black Belt",
    "1-Stripe Grey/Black Belt",
    "2-Stripe Grey/Black Belt",
    "3-Stripe Grey/Black Belt",
    "4-Stripe Grey/Black Belt",
    "Yellow/White Belt",
    "1-Stripe Yellow/White Belt",
    "2-Stripe Yellow/White Belt",
    "3-Stripe Yellow/White Belt",
    "4-Stripe Yellow/White Belt",
    "Yellow Belt",
    "1-Stripe Yellow Belt",
    "2-Stripe Yellow Belt",
    "3-Stripe Yellow Belt",
    "4-Stripe Yellow Belt",
    "Yellow/Black Belt",
    "1-Stripe Yellow/Black Belt",
    "2-Stripe Yellow/Black Belt",
    "3-Stripe Yellow/Black Belt",
    "4-Stripe Yellow/Black Belt",
    "Orange/White Belt",
    "1-Stripe Orange/White Belt",
    "2-Stripe Orange/White Belt",
    "3-Stripe Orange/White Belt",
    "4-Stripe Orange/White Belt",
    "Orange Belt",
    "1-Stripe Orange Belt",
    "2-Stripe Orange Belt",
    "3-Stripe Orange Belt",
    "4-Stripe Orange Belt",
    "Orange/Black Belt",
    "1-Stripe Orange/Black  Belt",
    "2-Stripe Orange/Black  Belt",
    "3-Stripe Orange/Black  Belt",
    "4-Stripe Orange/Black  Belt",
    "Green/White Belt",
    "1-Stripe Green/White Belt",
    "2-Stripe Green/White Belt",
    "3-Stripe Green/White Belt",
    "4-Stripe Green/White Belt",
    "Green Belt",
    "1-Stripe Green Belt",
    "2-Stripe Green Belt",
    "3-Stripe Green Belt",
    "4-Stripe Green Belt",
    "Green/Black Belt",
    "White Belt",
    "Phase 1 White Belt",
    "Phase 2 White Belt",
    "Phase 4 White Belt",
    "Phase 3 White Belt",
    "Blue Belt",
    "1-Stripe Blue Belt",
    "2-Stripe Blue Belt",
    "3-Stripe Blue Belt",
    "4-Stripe Blue Belt",
    "Purple Belt",
    "1-Stripe Purple Belt",
    "2-Stripe Purple Belt",
    "3-Stripe Purple Belt",
    "4-Stripe Purple Belt",
    "Brown Belt",
    "1-Stripe Brown Belt",
    "2-Stripe Brown Belt",
    "3-Stripe Brown Belt",
    "4-Stripe Brown Belt",
    "Black Belt"
]

export const mtRanks = [
    "White Pra Jiad",
    "Yellow/White Pra Jiad",
    "Yellow Pra Jiad",
    "Orange/White Pra Jiad",
	"Orange Pra Jiad",
    "Green/White Pra Jiad",
    "Green Pra Jiad",
    "Blue/White Pra Jiad",
    "Blue Pra Jiad",
    "Purple/White Pra Jiad",
    "Purple Pra Jiad",
    "Brown/White Pra Jiad",
    "Brown Pra Jiad",
    "Brown/Black Pra Jiad",
    "Black Pra Jiad",
    "Red Pra Jiad"

]